---

# overrides defaults in netbootxyz role
generate_menus: false 
generate_disks: true
generate_checksums: true
generate_local_vars: true
make_num_jobs: 1

# set desired site name
site_name: "{{ bootloader_tftpd_server | default('example.lab') }}" 

# set desired boot domain
boot_domain: "{{ site_name }}"

# set boot version
# boot_version: "2.x"

# bootloader_tftp_enabled: false
# bootloader_https_enabled: true
# bootloader_http_enabled: true

# set release overrides from standard netboot.xyz defaults
# release_overrides:
#   alpinelinux:
#     name: "Alpine Linux"
#   fedora:
#     mirror: "mirrors.kernel.org"

# set utilitiesefi_overrides from standard netboot.xyz defaults for EFI utilities
# utilitiesefi_overrides:
#  supergrub:
#    enabled: false

# set utilities_overrides from standard netboot.xyz defaults for PC BIOS utilities
# utilitiespcbios64_overrides:
#  supergrub:
#    enabled: false

early_menu_enabled: false
early_menu_contents: |
   ### early menu overrides
   ### used to set early ipxe options such as custom console & logo
   # console --x 1024 --y 768
   # console --picture https://boot.netboot.xyz/logo.png
