---
- name: Setup PXE Server 
  hosts: pxe_servers 
  rolesi:
    - role: cdg.local-repos
    - role: cdg.repos 
    - role: robertdebock.bootstrap
    - role: robertdebock.dnsmasq
    #- role: cdg.booloader
    #- role: cdg.installer
